#pragma kernel GenerateInnerCellVertices
#pragma kernel ApplyLevelOfDetail
#pragma kernel GenerateOuterCellVertices
#pragma kernel GenerateTriangles
#pragma kernel PackRenderVertices

#include "Assets/Compute/Voxels/Include/Cell.hlsl"
#include "Assets/Compute/Voxels/Include/Vertex.hlsl"
#include "Assets/Compute/Voxels/Include/Voxel2.hlsl"
#include "Assets/Compute/Voxels/Include/VoxelVolume.hlsl"

static const uint nullVertexIndex = -1;
static const uint maxNumberOfIntersections = 6;

struct CellVertexInfo
{
    uint index;

    static CellVertexInfo Create()
    {
        CellVertexInfo cellVertexInfo;
        cellVertexInfo.index = nullVertexIndex;

        return cellVertexInfo;
    }
};

struct GPUVertex
{
    float3 position;
    uint2 halfPrecisionNormal;
    uint2 packedMaterialSet;

    static GPUVertex Create(Vertex vertex)
    {
        GPUVertex gpuVertex;
        gpuVertex.position = vertex.position;
        gpuVertex.halfPrecisionNormal = vertex.halfPrecisionNormal;
        gpuVertex.packedMaterialSet = vertex.packedMaterialSet;

        return gpuVertex;
    }
};

struct Intersection
{
    float3 position;
    float3 normal;
    uint4 materialSetIndices;
    float4 materialSetWeights;

    static Intersection Create(
        float3 position = 0.0f,
        float3 normal = 0.0f,
        uint4 materialSetIndices = uint4(0, 0, 0, 0),
        float4 materialSetWeights = float4(1, 0, 0, 0))
    {
        Intersection intersection;
        intersection.position = position;
        intersection.normal = normal;
        intersection.materialSetIndices = materialSetIndices;
        intersection.materialSetWeights = materialSetWeights;

        return intersection;
    }
};

uint cellStride;
uint schmitzParticleIterations;
float schmitzParticleStepSize;

RWStructuredBuffer<CellVertexInfo> cellVertexInfoLookupTable;
RWStructuredBuffer<Vertex> generatedVertices0;
RWStructuredBuffer<Vertex> generatedVertices1;
RWStructuredBuffer<GPUVertex> generatedRenderVertices;
RWByteAddressBuffer generatedTriangles;

// Theoretically we can declare below arrays locally and pass them around functions with the "out" or "inout" modifier but that will
// result in more temporary registers being used by the compiler for some reason. See the following link for more information:
// https://gamedev.stackexchange.com/questions/190131/splitting-up-hlsl-code-into-separate-functions-causes-the-number-of-needed-tempo.
static uint numberOfIntersections;
static Intersection intersections[maxNumberOfIntersections];
static float materialSetWeightSums[16];
static float3 forces[numberOfCellCorners];
static CellVertexInfo neighbourCellVertexInfos[3];

bool IsOuterVoxel(uint3 coordinate)
{
    return any(coordinate == 0 || coordinate == numberOfVoxels - 2);
}

uint CalculateCellVertexInfoLookupTableIndex(uint3 coordinate, uint stride = 1)
{
    coordinate = IsOuterVoxel(coordinate) ? coordinate : (coordinate - 1) / stride * stride + 1;

    return dot(coordinate, uint3(1, numberOfVoxels.x - 1, (numberOfVoxels.x - 1) * (numberOfVoxels.y - 1)));
}

float3 CalculateCombinedForce(float3 center)
{
    float alpha = center.x;

    float3 force03 = alpha * forces[3] + (1.0f - alpha) * forces[0];
    float3 force47 = alpha * forces[7] + (1.0f - alpha) * forces[4];
    float3 force12 = alpha * forces[2] + (1.0f - alpha) * forces[1];
    float3 force56 = alpha * forces[6] + (1.0f - alpha) * forces[5];

    float beta = center.z;

    float3 force0347 = beta * force47 + (1.0f - beta) * force03;
    float3 force1256 = beta * force56 + (1.0f - beta) * force12;

    float gamma = center.y;

    return gamma * force1256 + (1.0f - gamma) * force0347;
}

float3 CalculateForce(float3 corner)
{
    float3 force = 0.0f;

    [unroll(maxNumberOfIntersections)]
    for (uint intersectionIndex = 0; intersectionIndex < numberOfIntersections; intersectionIndex++)
    {
        float3 position = intersections[intersectionIndex].position;
        float3 normal = intersections[intersectionIndex].normal;
        float distance = dot(normal, corner - position);
        float3 voxelCornerToPlaneVector = -distance * normal;

        force += voxelCornerToPlaneVector;
    }

    return force;
}

void ResetMaterialSetWeightSums()
{
    [unroll]
    for (uint materialIndex = 0; materialIndex < 16; materialIndex++)
    {
        materialSetWeightSums[materialIndex] = 0.0f;
    }
}

void AccumulateMaterialSet(uint4 materialSetIndices, float4 materialSetWeights)
{
    [unroll]
    for (uint index = 0; index < 4; index++)
    {
        materialSetWeightSums[materialSetIndices[index]] += materialSetWeights[index];
    }
}

void BuildMaterialSet(out uint4 materialSetIndices, out float4 materialSetWeights)
{
    materialSetIndices = 0;
    materialSetWeights = 0.0f;

    [unroll]
    for (uint materialIndex = 0; materialIndex < 16; materialIndex++)
    {
        float weight = materialSetWeightSums[materialIndex];

        if (weight > materialSetWeights.x)
        {
            materialSetWeights.w = materialSetWeights.z;
            materialSetIndices.w = materialSetIndices.z;
            materialSetWeights.z = materialSetWeights.y;
            materialSetIndices.z = materialSetIndices.y;
            materialSetWeights.y = materialSetWeights.x;
            materialSetIndices.y = materialSetIndices.x;
            materialSetWeights.x = weight;
            materialSetIndices.x = materialIndex;
        }
        else if (weight > materialSetWeights.y)
        {
            materialSetWeights.w = materialSetWeights.z;
            materialSetIndices.w = materialSetIndices.z;
            materialSetWeights.z = materialSetWeights.y;
            materialSetIndices.z = materialSetIndices.y;
            materialSetWeights.y = weight;
            materialSetIndices.y = materialIndex;
        }
        else if (weight > materialSetWeights.z)
        {
            materialSetWeights.w = materialSetWeights.z;
            materialSetIndices.w = materialSetIndices.z;
            materialSetWeights.z = weight;
            materialSetIndices.z = materialIndex;
        }
        else if (weight > materialSetWeights.w)
        {
            materialSetWeights.w = weight;
            materialSetIndices.w = materialIndex;
        }
    }

    float sum = materialSetWeights.x + materialSetWeights.y + materialSetWeights.z + materialSetWeights.w;

    if (sum > 0.0001f)
    {
        materialSetWeights /= sum;
    }
    else
    {
        materialSetIndices = uint4(materialSetIndices.x, 0, 0, 0);
        materialSetWeights = float4(1, 0, 0, 0);
    }
}

Vertex CalculateCenterVertex()
{
    Vertex vertex = Vertex::Create();
    ResetMaterialSetWeightSums();

    [unroll(maxNumberOfIntersections)]
    for (uint intersectionIndex = 0; intersectionIndex < numberOfIntersections; intersectionIndex++)
    {
        Intersection intersection = intersections[intersectionIndex];

        vertex.SetPosition(vertex.GetPosition() + intersection.position);
        vertex.SetNormal(vertex.GetNormal() + intersection.normal);
        AccumulateMaterialSet(intersection.materialSetIndices, intersection.materialSetWeights);
    }

    vertex.SetPosition(vertex.GetPosition() / numberOfIntersections);
    vertex.SetNormal(normalize(vertex.GetNormal()));

    uint4 materialSetIndices;
    float4 materialSetWeights;
    BuildMaterialSet(materialSetIndices, materialSetWeights);
    vertex.SetMaterialSet(materialSetIndices, materialSetWeights);

    return vertex;
}

Vertex CalculateCellVertex(uint3 coordinate)
{
    Vertex vertex = CalculateCenterVertex();

    for (uint cornerIndex = 0; cornerIndex < numberOfCellCorners; cornerIndex++)
    {
        forces[cornerIndex] = CalculateForce(cellCorners[cornerIndex]);
    }

    for (uint schmitzParticleIteration = 0; schmitzParticleIteration < schmitzParticleIterations; schmitzParticleIteration++)
    {
        vertex.SetPosition(vertex.GetPosition() + schmitzParticleStepSize * CalculateCombinedForce(vertex.GetPosition()));
    }
    vertex.SetPosition(VoxelToVoxelVolumeSpace(coordinate, vertex.GetPosition()));

    return vertex;
}

void CalculatePositionsAndNormals(uint3 coordinate)
{
    numberOfIntersections = 0;

    for (uint cellEdgeIndex = 0; cellEdgeIndex < numberOfCellEdges; cellEdgeIndex++)
    {
        CellEdge cellEdge = cellEdges[cellEdgeIndex];

        uint3 cellCornerA = cellCorners[cellEdge.GetCornerStartIndex()];
        uint3 cellCornerB = cellCorners[cellEdge.GetCornerEndIndex()];

        Voxel sampleA = GetVoxel(coordinate + cellCornerA);
        Voxel sampleB = GetVoxel(coordinate + cellCornerB);

        if (sampleA.IsSolid() == sampleB.IsSolid())
        {
            continue;
        }

        float interpolant = -sampleA.GetValue() / (sampleB.GetValue() - sampleA.GetValue());
        Voxel surfaceSample;

        if (!sampleA.IsSolid())
        {
            surfaceSample = sampleA;
        }
        else
        {
            surfaceSample = sampleB;
        }

        intersections[numberOfIntersections++] = Intersection::Create
        (
            lerp(cellCornerA, cellCornerB, interpolant),
            normalize(lerp(sampleA.GetGradient(), sampleB.GetGradient(), interpolant)),
            surfaceSample.materialSetIndices,
            surfaceSample.materialSetWeights
        );
    }
}

[numthreads(4, 4, 4)]
void GenerateInnerCellVertices(uint3 id : SV_DispatchThreadID)
{
    uint3 cellID = id + 1;

    if (any(cellID > numberOfVoxels - 3))
    {
        return;
    }

    CellVertexInfo cellVertexInfo = CellVertexInfo::Create();

    CalculatePositionsAndNormals(cellID);

    if (numberOfIntersections > 0)
    {
        cellVertexInfo.index = generatedVertices0.IncrementCounter();
        generatedVertices0[cellVertexInfo.index] = CalculateCellVertex(cellID);
    }
    cellVertexInfoLookupTable[CalculateCellVertexInfoLookupTableIndex(cellID)] = cellVertexInfo;
}

[numthreads(4, 4, 4)]
void ApplyLevelOfDetail(uint3 id : SV_DispatchThreadID)
{
    uint3 cellID = id * cellStride + 1;

    if (any(cellID > numberOfVoxels - 3))
    {
        return;
    }

    uint numberOfChildCellVertices = 0;
    CellVertexInfo parentCellVertexInfo = CellVertexInfo::Create();
    Vertex parentCellVertex = Vertex::Create();
    ResetMaterialSetWeightSums();

    for (uint cornerIndex = 0; cornerIndex < numberOfCellCorners; cornerIndex++)
    {
        uint3 coordinate = cellID + cellStride / 2 * cellCorners[cornerIndex];
        CellVertexInfo childCellVertexInfo = cellVertexInfoLookupTable[CalculateCellVertexInfoLookupTableIndex(coordinate, cellStride / 2)];

        if (childCellVertexInfo.index != nullVertexIndex)
        {
            Vertex childCellVertex = generatedVertices0[childCellVertexInfo.index];

            parentCellVertex.SetPosition(parentCellVertex.GetPosition() + childCellVertex.GetPosition());
            parentCellVertex.SetNormal(parentCellVertex.GetNormal() + childCellVertex.GetNormal());
            uint4 materialSetIndices;
            float4 materialSetWeights;
            childCellVertex.GetMaterialSet(materialSetIndices, materialSetWeights);
            AccumulateMaterialSet(materialSetIndices, materialSetWeights);

            numberOfChildCellVertices++;
        }
    }

    if (numberOfChildCellVertices > 0)
    {
        parentCellVertex.SetPosition(parentCellVertex.GetPosition() / numberOfChildCellVertices);
        parentCellVertex.SetNormal(normalize(parentCellVertex.GetNormal()));
        uint4 materialSetIndices;
        float4 materialSetWeights;
        BuildMaterialSet(materialSetIndices, materialSetWeights);
        parentCellVertex.SetMaterialSet(materialSetIndices, materialSetWeights);

        parentCellVertexInfo.index = generatedVertices1.IncrementCounter();
        generatedVertices1[parentCellVertexInfo.index] = parentCellVertex;
    }

    cellVertexInfoLookupTable[CalculateCellVertexInfoLookupTableIndex(cellID, cellStride)] = parentCellVertexInfo;
}

[numthreads(4, 4, 4)]
void GenerateOuterCellVertices(uint3 cellID : SV_DispatchThreadID)
{
    if (any(cellID > numberOfVoxels - 2) || !IsOuterVoxel(cellID))
    {
        return;
    }

    CellVertexInfo cellVertexInfo = CellVertexInfo::Create();

    CalculatePositionsAndNormals(cellID);

    if (numberOfIntersections > 0)
    {
        cellVertexInfo.index = generatedVertices0.IncrementCounter();
        generatedVertices0[cellVertexInfo.index] = CalculateCellVertex(cellID);
    }
    cellVertexInfoLookupTable[CalculateCellVertexInfoLookupTableIndex(cellID)] = cellVertexInfo;
}

bool ArePairwiseDistinct(uint3 indices)
{
    return indices.x != indices.y && indices.x != indices.z && indices.y != indices.z;
}

void GenerateTriangle(CellVertexInfo cellVertexInfo, CellVertexInfo firstNeighbourCellVertexInfo, CellVertexInfo secondNeighbourCellVertexInfo)
{
    uint3 indices = uint3(cellVertexInfo.index, firstNeighbourCellVertexInfo.index, secondNeighbourCellVertexInfo.index);

    if (!ArePairwiseDistinct(indices))
    {
        return;
    }

    // The first 8 bytes of the generated triangles buffer will be used to store the number of vertices/triangles
    // generated and therefore need to stay empty.
    generatedTriangles.Store3(8 + 12 * cellVertexInfoLookupTable.IncrementCounter(), indices);
}

void GetNeighbourCellsVertexInfos(uint3 coordinate, uint index)
{
    const uint3 cellCornerIndices[3] =
    {
        uint3(1, 2, 3),
        uint3(4, 5, 1),
        uint3(3, 7, 4)
    };

    uint3 vertexIndices;

    [unroll]
    for (uint iterator = 0; iterator < 3; iterator++)
    {
        neighbourCellVertexInfos[iterator] = cellVertexInfoLookupTable[CalculateCellVertexInfoLookupTableIndex(coordinate + cellCorners[cellCornerIndices[index][iterator]], cellStride)];
    }
}

CellEdge GetCellEdge(uint index)
{
    const uint3 edgeIndices = uint3(5, 6, 10);

    return cellEdges[edgeIndices[index]];
}

[numthreads(4, 4, 4)]
void GenerateTriangles(uint3 cellID : SV_DispatchThreadID)
{
    if (any(cellID > numberOfVoxels - 3))
    {
        return;
    }

    CellVertexInfo cellVertexInfo = cellVertexInfoLookupTable[CalculateCellVertexInfoLookupTableIndex(cellID, cellStride)];

    for (uint index = 0; index < 3; index++)
    {
        CellEdge cellEdge = GetCellEdge(index);

        Voxel sampleA = GetVoxel(cellID + cellCorners[cellEdge.GetCornerStartIndex()]);
        Voxel sampleB = GetVoxel(cellID + cellCorners[cellEdge.GetCornerEndIndex()]);

        if (sampleA.IsSolid() == sampleB.IsSolid())
        {
            continue;
        }

        GetNeighbourCellsVertexInfos(cellID, index);

        for (uint triangleIndex = 0; triangleIndex < 2; triangleIndex++)
        {
            CellVertexInfo firstNeighbourCellVertexInfo = neighbourCellVertexInfos[sampleB.GetValue() < 0.0f ? triangleIndex : triangleIndex + 1];
            CellVertexInfo secondNeighbourCellVertexInfo = neighbourCellVertexInfos[sampleB.GetValue() < 0.0f ? triangleIndex + 1 : triangleIndex];
            GenerateTriangle(cellVertexInfo, firstNeighbourCellVertexInfo, secondNeighbourCellVertexInfo);
        }
    }
}

[numthreads(64, 1, 1)]
void PackRenderVertices(uint3 id : SV_DispatchThreadID)
{
    uint vertexIndex = id.x;
    uint vertexCount = generatedTriangles.Load(0);

    if (vertexIndex >= vertexCount)
    {
        return;
    }

    generatedRenderVertices[vertexIndex] = GPUVertex::Create(generatedVertices0[vertexIndex]);
}
